### ISSUE TITLE
So about loading the mod

### ISSUE THREAD

**Issue by megaspider01** [napoleons-legacy/mod#11]
Hey I think it's great you're working on the mod, it is a bit bearboned right now but has so good potential. Just wanted to point out that the mod crashed on "databases II" when loading and was only fixed by using the oldest version available here on Github. Therefore I think one of your changes might have caused this, so it'd be great if you looked into it.

If you want any help with the mod I could try to help. I don't really mod anymore but I could give thoughts and suggestions.

**Comment by nappys-legacy** [comment]
Sorry for the late reply, I'll check out what went wrong!

If you want to help out with the mod, I'd really just like suggestions on how to improve the mod. Some points of discussion would be the entire situation of Europe and how France relates to the entire continent. I have some really interesting ideas, I just need the time to revamp the entire world system. Before the pause I was working on reworking North America (I was planning on going left -> right across the map so they were first) because it's rather dull as it is.

Another REALLY useful thing would be dealing with HPM and its updates. It looks like HPM 0.4 came out with a large amount of changes. I really just want to port over economic changes, population in non-divergent areas, and other things that can be adapted that are more dynamic and less railroad-ey

**Comment by nappys-legacy** [comment]
I see nothing wrong when starting the mod on a fresh installation of Vic 2 with the current version?
I am on macOS though, but I doubt thats an issue.

I'll close the issue, if anything comes up let me know

**Comment by nappys-legacy** [comment]
I keep seeing people mentioning this in /gsg/ so I dont think its fixed oof

**Comment by nappys-legacy** [comment]
It's finally fixed so I can close this, turns out there was an invention that referenced christino_rebels when it wasn't defined (removed) and apparently that doesn't cause a crash in macOS but does in Windows.
